// Karnataka Engineering Colleges Data
export const KARNATAKA_COLLEGES = [
  "A J Institute of Engineering, Dakshin Kannad",
  "Acharya Institute of Technology, Bengaluru",
  "Acharyar NRV School of Architecture, Bengaluru",
  "Adichunchanagiri Institute of Technology, Chikkamagaluru",
  "Aditya Academy of Architecture, Bengaluru",
  "Alvas Institute of Engineering, Dakshin Kannad",
  "AMG Rural College of Engineering, Dharwad",
  "Amruta Institute of Engineering, Bidadi, Bengaluru",
  "ANJUMAN Institute of Technology, Uttar Kannad",
  "APS College of Engineering, Bengaluru",
  "Appa Institute of Engineering & Technology, Kalaburagi",
  "B G S Institute of Technology, Mandya",
  "B M S (Even) College of Engineering, Bengaluru",
  "B M S College of Engineering, Bengaluru",
  "B M S College of Architecture, Bengaluru",
  "B N M Institute of Technology, Bengaluru",
  "B T L Institute of Technology Management, Bengaluru",
  "Bapuji Institute of Engineering, Davangere",
  "Basava Kalyan Engineering College, Bidar",
  "Basaveshwar Engineering College, Bagalkot",
  "BASAV Engineering School of, Vijayapura",
  "Bearys Institute of Technology, Dakshin Kannad",
  "Biluru Gurubasava Mahaswamiji Institute of Technology,Mudhol, Bagalkot",
  "BMS School of Architecture, Bengaluru",
  "Brindavan College of Engg., Bengaluru Urban",
  "C M R Institute of Technology, Bengaluru",
  "Cauvery Institute of Technology, Mandya",
  "Cambridge Institute of Technology, Bengaluru",
  "Canara Engineering College, Dakshin Kannad",
  "Channabasaveshwara Institute, Tumakuru",
  "City Engineering College, Bengaluru",
  "Dayananda Sagar College of, Bengaluru Urban",
  "Dayananda Sagar College of Architecture, Bengaluru",
  "Don Bosco Institute of Technology, Bengaluru",
  "East Point College of Engg., Bengaluru",
  "East West Institute of Technology, Bengaluru",
  "East West School of Architecture, Bengaluru",
  "East West College of Engineering, Bengaluru",
  "Ekalavya Institute of Technology, Chamarajanagar",
  "G M Institute of Technology, Davangere",
  "G Madegowda Institute of, Mandya",
  "G S S S Institute of Engineering, Mysuru",
  "Gogte Institute of Technology, Belagavi",
  "Gopalan College of Engineering, Bengaluru",
  "Gopalan School of Architecture, Bengaluru",
  "Govind B. P. Institute of Technology, Bidar",
  "Government Engineering College, Ballari",
  "Government Engineering College, Chamarajanagar",
  "Government Engineering College, Dakshin Kannad",
  "Government Engineering College, Hassan",
  "Government Engineering College, Haveri",
  "Government Engineering College, Koppal",
  "Govt. S K S J Technological Institute, Bengaluru",
  "Govt. Tool Room & Training, Bengaluru",
  "H K B K College of Engineering, Bengaluru",
  "H M S Institute of Technology, Tumkur",
  "HMS School of Architecture, Tumakuru",
  "Hirasugar Institute of Technology, Belagavi",
  "Honeywell Technologies Solutions, Bengaluru",
  "Impact College of Engineering, Bengaluru",
  "Impact School of Architecture, Bengaluru",
  "Islamiah Inst. of Technology, Bengaluru",
  "J N N College of Engineering, Shivamogga",
  "Jain Acharya Gundharnandi Maharaj, Bagalkot",
  "Jain College of Engineering, Belagavi",
  "Jain College of Engineering, Dharwad",
  "Jain Institute of Technology, Davangere",
  "JAIN COLLEGE OF ENGINEERING, Belagavi",
  "JAIN COLLEGE OF ENGINEERING, Dharwad",
  "Jnana Vikas Institute of Technology, Bengaluru",
  "J S S Academy of Technical Education, Bengaluru",
  "J S C Institute of Technology, Chickballapur",
  "Jyothy Institute of Technology, Bengaluru",
  "K L Es College of Engg. & Technology, Belagavi",
  "K N S Institute of Technology, Bengaluru",
  "K S Institute of Technology, Bengaluru",
  "K S School of Architecture, Bengaluru",
  "K S School of Engineering & Management, Bengaluru",
  "K T C Engineering College, Kalaburagi",
  "Kalpataru Institute of Technology, Tumakuru",
  "Karavali Institute of Technology, Dakshin Kannad",
  "KLE Institute of Technology, Hubli",
  "KLEs College of Engineering & Technology, Belagavi",
  "K V G College of Engineering, Dakshin Kannad",
  "Lingaraj Appa Engineering, Bidar",
  "M S Engineering College, Bengaluru",
  "M S Ramaiah Institute of Technology, Bengaluru",
  "Malnad College of Engineering, Hassan",
  "Malik Sandal Institute of Arts & Architecture, Vijayapura",
  "Maharaja Institute of Technology, Mysuru",
  "Mangalore Institute of Technology, Dakshin Kannad",
  "Mangalore Marine College and, Dakshin Kannad",
  "Maratha Mandal Engineering, Belagavi",
  "Moodalkatte Institute of Technology, Udupi",
  "Mysore College of Engineering, Mysuru",
  "Mysore School of Architecture, Mysuru",
  "Mysuru Royal Institute of, Mandya",
  "Nagarjuna College of Engg., Bengaluru",
  "NDRK Institute of Technology, Hassan",
  "NE Institute of Engineering, Mysuru",
  "Nitte Meenakshi Institute of, Bengaluru",
  "Nitte School of Architecture, Bengaluru",
  "NMAM Institute of Technology, Udupi",
  "P A College of Engineering, Mangalore",
  "PDA College of Engineering, Kalaburagi",
  "PES College of Engineering, Mandya",
  "PES Institute of Technology, Shivamogga",
  "Proudadevaraya Institute of Technology, Ballari",
  "Rajeev Institute of Technology, Hassan",
  "Rajarajeshwari College of Engineering, Bengaluru",
  "Rajiv Gandhi Institute of Technology, Bengaluru",
  "Rao Bahaddur Y Mahabaleshwa, Ballari",
  "R L Jalappa Institute of Technology, Chikballapur",
  "R N S Institute of Technology, Bengaluru",
  "R T Nagar Post, Bengaluru",
  "RD Institute of Technology, Bengaluru",
  "RNS School of Architecture, Bengaluru",
  "R V College of Architecture, Bengaluru",
  "R V College of Engineering, Bengaluru",
  "S J M Institute of Technology, Chitradurga",
  "S J B Institute of Technology, Bengaluru",
  "S J C Institute of Technology, Chickballapur",
  "S J S Academy of Technical Education, Bengaluru",
  "SJB School of Architecture, Bengaluru",
  "S G Balekundri Institute of Technology, Belagavi",
  "S K S J Technological Institute (Eve), Bengaluru",
  "S L N College of Raichur",
  "S M V School of Architecture, Bengaluru",
  "Sakshiganga College of Engineering, Mysuru",
  "Sahyadri College of Engineering, Dakshin Kannad",
  "Sampoorna Institute of Technology, Ramanagara",
  "Sapthagiri College of Engineering, Bengaluru",
  "Sathyabama Institute of Science and Technology",
  "Shaikh College of Engineering & Technology, Belagavi",
  "Shridevi Institute of Engineering, Tumakuru",
  "Shri Madhwa Vadiraja Institute of, Udupi",
  "Shree Devi Institute of Technology, Dakshin Kannad",
  "Shree Vinayaka Institute of, Kolar",
  "Shushrutha Institute of Medical Sciences and Research Centre",
  "Smt. Kamala & Sri Venkappa M Agadi, Gadag",
  "Srinivas Institute of Technology, Dakshin Kannad",
  "Sri Basaveshwara Institute of, Tumakuru",
  "Sri Krishana Institute of Technology, Bengaluru",
  "Sri Sairam College of Engineering, Bengaluru",
  "ST J Institute of Technology, Ranebennur",
  "St Joseph Engineering College, Dakshin Kannad",
  "Tontadarya College of Engineering, Gadag",
  "VTU Extension Centre, Bengaluru",
  "VTU Extension Centre, IR Rasta, Bengaluru",
  "VTU Extension Center, N M A Dakshin Kannad",
  "Vemana Institute of Technology, Bengaluru",
  "Veerappa Nisty Engineering, Kalaburagi",
  "Vijaya Vittal Institute of Technology, Bengaluru",
  "Vidya Vikas Institute of Technology, Mysuru",
  "Vishwanathrao Deshpande Institute of, Uttar Kannad",
  "Visvesvaraya Technological University, Belagavi",
  "Visvesvaraya Technological University, Chikballapur",
  "Visvesvaraya Technological University, Kalaburagi",
  "Vivekananda College of Engineering & Tech., Dakshin Kannad",
  "Vivekananda Institute of Technology, Bengaluru Rural",
  "Wadiyar Centre for Architecture, Mysuru",
  "Yenepoya Institute of Technology, Dakshin Kannad",
  "Zain University, Karnataka"
];

export const ENGINEERING_BRANCHES = [
  "Computer Science & Engineering",
  "Artificial Intelligence & Machine Learning",
  "Artificial Intelligence and Data Science",
  "Information Science Engineering",
  "Electronics & Communication Engineering",
  "Electrical and Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering"
];

export const SEMESTERS = [
  "1st Semester",
  "2nd Semester",
  "3rd Semester",
  "4th Semester",
  "5th Semester",
  "6th Semester",
  "7th Semester",
  "8th Semester"
];
